import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.johnrengelman.shadow") version "8.1.1"
    `java-library`
    `maven-publish`
    kotlin("jvm")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repository.jboss.org/nexus/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))

    api(libs.io.netty.netty.all)
    runtimeOnly(libs.hsqldb.hsqldb)


    testImplementation(kotlin("test"))
}

tasks.shadowJar {
    manifest.attributes.apply {
        put("Main-Class", "net.sf.opensmus.OpenSMUS")
    }
}

tasks.test {
    useJUnitPlatform()
}

group = "net.sf.opensmus"
version = "2.0.0-SNAPSHOT"
description = "OpenSMUS server"
//java.sourceCompatibility = JavaVersion.VERSION_1_5
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "21"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "21"
}